// Generated by CoffeeScript 1.10.0
(function() {
  var Promise;

  require('colors');

  Promise = require('bluebird');

  Promise.config({
    warnings: true,
    longStackTraces: true
  });

  Promise.onPossiblyUnhandledRejection(function(err) {
    console.log('onPossiblyUnhandledRejection'.red, err);
    throw err;
  });

  exports.serverOpts = {
    port: 5984,
    hostname: 'localhost',
    user: 'admin',
    pass: 'admin'
  };

  exports.dbName = 'test-cot-node';

}).call(this);
