// Source: https://docs.couchdb.org/en/latest/api/ddoc/views.html
export const viewQueryKeys = {
  conflicts: 'boolean',
  descending: 'boolean',
  endkey: 'json',
  end_key: 'json',
  endkey_docid: 'string',
  end_key_doc_id: 'string',
  group: 'boolean',
  group_level: 'number',
  include_docs: 'boolean',
  attachments: 'boolean',
  att_encoding_info: 'boolean',
  inclusive_end: 'boolean',
  key: 'json',
  keys: 'json',
  limit: 'number',
  reduce: 'boolean',
  skip: 'number',
  sorted: 'boolean',
  stable: 'boolean',
  stale: 'string',
  startkey: 'json',
  start_key: 'json',
  startkey_docid: 'string',
  start_key_doc_id: 'string',
  update: 'string',
  update_seq: 'boolean',
}

// Source: https://docs.couchdb.org/en/latest/api/database/changes.html
export const changesQueryKeys = {
  doc_ids: 'json',
  conflicts: 'boolean',
  descending: 'boolean',
  // Not including feed as a possible option as it doesn't play well with promises
  // feed: 'string',
  filter: 'string',
  heartbeat: 'number',
  include_docs: 'boolean',
  attachments: 'boolean',
  att_encoding_info: 'boolean',
  'last-event-id': 'number',
  limit: 'number',
  style: 'string',
  since: 'string',
  timeout: 'number',
  view: 'string',
  seq_interval: 'number',
}
